[package]
name = "learningrust"
version = "0.1.0"
authors = ["tarajohns0n <johnson.tara5@student.oaklandcc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
